# Production-only server configuration
debug: false
base_url: https://proxyslots.com
google:
  email: hectasoft@googlegroups.com
  id: 23500177865-sjci2li883c6ihpth0cmfa984absvf51.apps.googleusercontent.com
  secret: NB7dXMiS9qnqFxaTGC7UkCPR
  redirect_uri: https://proxyslots.com/auth/google/callback
stripe:
  secret: sk_live_oSuXXmjaHuBaQaVwHTyw9AbO # Change public when you see this :)
paypal:
  account: none
  id: none
  secret: none
coin_payments:
  public: d517aa026da41f0753fb5909002d26a1f8e7e6a38b5dff75e60b2c1c96bc2045
  private: E4A0787c1857A1Ce86f5861dDa94881d587631EC81157c5f167cDF345aC914e1
  ipn_secret: 3xiwqAj8YeH2GuadIAmb
  merchant_id: 5390a5a06c77ef0144a4e7906ad467a2